language: node_js
node_js:
  - 0.10
  - 0.12
	- iojs

before_install:
  - mkdir node_modules; ln -s ../ node_modules/webmake-coffee

notifications:
  email:
    - medikoo+webmake-coffee@medikoo.com

script: "npm test && npm run lint"
